---
talons:
  driveLeft: # Talon
    deviceNumber: 1
    type: BRUSHLESS
    subsystemName: Drive
    peakCurrentDuration: 0
    peakCurrentLimit: 0
    enableVoltageCompensation: true
    compSaturationVoltage: 12
    continuousCurrentLimitAmps: 30
    motionAcceleration: 0
    motionCruiseVelocity: 0
    closedLoopRampRate: 0
    openLoopRampRate: 0
    invertSensorPhase: true
    statusFrame: STATUS_2
    followers:
      - id: 2
        type: BRUSHLESS
        inverted: FOLLOW_LEADER
    inverted: NONINVERTED
    pidControllers:
      - p: 0.00013
        i: 0
        d: 0
        f: 0
        maxVelocity: 18000
        maxAcceleration: 45000
        maxIntegralAccumulator: 0
        integralZone: 0
        allowableClosedLoopError: 0
  driveRight: #Talon
    deviceNumber: 3
    type: BRUSHLESS
    subsystemName: Drive
    peakCurrentDuration: 0
    peakCurrentLimit: 0
    enableVoltageCompensation: true
    compSaturationVoltage: 12
    continuousCurrentLimitAmps: 30
    motionAcceleration: 0
    motionCruiseVelocity: 0
    closedLoopRampRate: 0
    openLoopRampRate: 0
    invertSensorPhase: true
    statusFrame: STATUS_2
    followers:
      - id: 4
        type: BRUSHLESS
        inverted: FOLLOW_LEADER
    inverted: INVERTED
    pidControllers:
      - p: 0.00013
        i: 0
        d: 0
        f: 0
        maxVelocity: 18000
        maxAcceleration: 45000
        maxIntegralAccumulator: 0
        integralZone: 0
        allowableClosedLoopError: 0
sparks:
  shooter:
    deviceNumber: 15
    type: BRUSHLESS
    subsystemName: Shooter
    peakCurrentDuration: 0
      peakCurrentLimit: 0
      enableVoltageCompensation: true
      compSaturationVoltage: 12
      continuousCurrentLimitAmps: 30
      motionAcceleration: 0
      motionCruiseVelocity: 0
      closedLoopRampRate: 0
      openLoopRampRate: 0
      invertSensorPhase: true
      statusFrame: STATUS_2
      inverted: NONINVERTED
victors:
...
